### ISSUE TITLE
CSS variables are broken after compilation

### ISSUE THREAD

**Issue by tsrivishnu** [rails/sprockets#743]
### Expected behavior

I have a CSS file the following contents that contain a custom property `--262c2734`

```css
@-webkit-keyframes expand-enter-4fe57568 {
  100% {
    height: var(--262c2734);
  }
}
```

When I run `rake assets:precompile`, I expect this resulting compressed CSS file to not have broken custom property.

### Actual behavior

The dashes `--` in the custom property  are removed the resulting contents are as following:

```css
@-webkit-keyframes expand-enter-4fe57568{100%{height:var(262c2734)}}
```

### System configuration

- Sprockets version  4.0.2
- Ruby version 2.7.4

### Example App (Reproduction) 

Rails app setup to reproduce the issue: https://github.com/tsrivishnu/tmp-rails-sprockets-css-custom-props-issues
